### PR TITLE
adding config options to eth_testnet_config

### PR DESCRIPTION
**Pull request by parithosh**
this is needed as the repo cloned doesn't always contain the files needed by the node at its root. this change allows us to clone the repo to a temp location and then move the required files to the needed destination.

### CODE REVIEW

**Comment by parithosh** [comment]
Don't merge it in, something is off when i re-ran it. potentially got to do with the renaming of the network-config/nft-devnet-0 folder. yet to dig in and clean up

**Comment by parithosh** [comment]
its working now, fixed the bug

**Comment by barnabasbusa** [comment]
@parithosh this good to go?

**Comment by parithosh** [comment]
yessir, good to merge in. I used it on the nft devnets repo and everything worked fine.

**Pull request merged**
