### PR TITLE
add call rate limits to dora

### PR DESCRIPTION
**Pull request by pk910**

### CODE REVIEW

**Review by barnabasbusa — APPROVED** [review]

**Comment by Samer26886** [comment]
Hello, I want to contact you. It is very necessary. This WhatsApp number is +201140794623.

**Comment by parithosh** [comment]
@Samer26886 if its important for you, please run your own node as well as your locally hosted version of Dora. We're unable to support high request loads on our machines currently, this is an explorer meant to help testing teams and not one for public consumption.

I can also recommend beaconcha.in, they also have a paid API with very liberal limits.

**Comment by Samer26886** [comment]
Firstly, thank you for your interest. Secondly, I am still a beginner and I do not know what you mean or how I can run the contract at all. This is the reason for communication. Firstly, learning. Secondly, can we make the test codes to be real?

**Comment by parithosh** [comment]
What is it that you want to run or do? There is no contract on the explorer and i don't know what you mean by test codes.

**Pull request merged**
