### PR TITLE
add chrony

### PR DESCRIPTION
**Pull request by barnabasbusa**

### CODE REVIEW

**Comment by parithosh** [comment]
Installing it won't be enough, you have to enable it on systemd and start the service as well

**Review by parithosh — APPROVED** [review]

**Comment by skylenet** [comment]
FYI:  Instead of having it added on the roles defaults, you could have also overwritten the `bootstrap_default_common_packages` for the specific environment where you want to have chrony. This would make more sense when we don't need a specific package by default on all our VMs across all envs.

**Comment by barnabasbusa** [comment]
I do feel like we probably want a chrony running on all of our machines tho. As having no ntp configured on it gonna cause issues later too.

**Comment by parithosh** [comment]
Yea I agree, I think chrony as a sane default makes sense irrespective of the machine

**Pull request merged**
